### ISSUE TITLE
POST /util/validateAddress returning incorrect results

### ISSUE THREAD

**Issue by ProtocolCash** [Bitcoin-com/rest.bitcoin.com#398] opened 2019-04-25 20:18 UTC
You can see it is even broken in the example at https://rest.bitcoin.com/#/util/validateAddressBulk

Instead of returning a list of objects, it returns the first object multiple times.

`curl -X POST "https://rest.bitcoin.com/v2/util/validateAddress" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"addresses\":[\"bitcoincash:qzs02v05l7qs5s24srqju498qu55dwuj0cx5ehjm2c\",\"bitcoincash:qrehqueqhw629p6e57994436w730t4rzasnly00ht0\"]}"`

Results in:

`[
  {
    "isvalid": true,
    "address": "bitcoincash:qrehqueqhw629p6e57994436w730t4rzasnly00ht0",
    "scriptPubKey": "76a914f3707320bbb4a28759a78a5ad63a77a2f5d462ec88ac",
    "ismine": false,
    "iswatchonly": false,
    "isscript": false
  },
  {
    "isvalid": true,
    "address": "bitcoincash:qrehqueqhw629p6e57994436w730t4rzasnly00ht0",
    "scriptPubKey": "76a914f3707320bbb4a28759a78a5ad63a77a2f5d462ec88ac",
    "ismine": false,
    "iswatchonly": false,
    "isscript": false
  }
]`

Notice only the qrehqueqhw629p6e57994436w730t4rzasnly00ht0 result is returned, multiple times.

**Comment by christroutner** [comment] 2019-04-25 23:32
Great find. Thanks!

**Comment by ProtocolCash** [comment] 2019-04-26 09:57
Another broken multi-result endpoint:

`curl -X POST "https://rest.bitcoin.com/v2/block/detailsByHeight" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"heights\":[579910,579921]}"`

It retuns the same block twice. This time, the second one - 579921.

**Comment by ProtocolCash** [comment] 2019-04-26 19:19
`/blockchain/getMempoolEntry`

is also broken in the same way - this one is particularly nasty because the returned objects don't have the txid.

**Comment by ProtocolCash** [comment] 2019-04-26 20:05
`/blockchain/getTxOutProof`
and
`/blockchain/verifyTxOutProof`
also broken

**Comment by ProtocolCash** [comment] 2019-04-26 21:52
`rawtransactions/decodeRawTransaction`
also affected

**Comment by ProtocolCash** [comment] 2019-04-26 22:06
`rawtransactions/decodeScript`
too

**Comment by christroutner** [comment] 2019-05-02 16:35
I'm working on a series of bug fixes for these endpoints. Thanks again for investigating this @ProtocolCash!

The source of the bugs is that we are querying data from the full node using parallel calls to the JSON RPC. If the full node is busy working on a request, it will return the data from the last request.

That behavior forces us to make calls in-series rather than in-parallel, which significantly slows down the response time. These are the code changes I'm in the process of implementing.

Here's an example that I just verified this morning: If you make two sequential calls to the RPC call `validateaddress` with two addresses, the node will return the second result twice. The second request essentially 'overwrites' the first request.

I reported this behavior to the ABC development team, but they are spread too thin to do anything about it. We can expect this behavior to persist into the future.

**Comment by christroutner** [comment] 2019-05-02 16:37
@GitCash send $5 to @ProtocolCash

**Comment by GitCash** [comment] 2019-05-02 16:37
Hey **ProtocolCash**, user **christroutner** tipped you **19011 bits** in Bitcoin Cash ( ~ **$5** ).

*[Click here to claim it!](https://gitcash.io/claim/ProtocolCash)*

You can also add the "thumbs down" reaction to **christroutner**'s comment above to prevent future tips.

**Comment by christroutner** [comment] 2019-05-02 18:21
The plot thickens. The bug **does not** appear to stem from parallel calls. I created this repo to prove out my hypothesis, and it proved that my hypothesis was wrong.
https://github.com/christroutner/full-node-parallel-test

I'm continuing to dig in and find the source of these bugs. The above test seems to indicate the issue is with the *way* we are making parallel calls, not in the actual parallel calls themselves.

**Comment by cgcardona** [comment] 2019-05-07 08:37
This is resolved in REST v3.4.0. Thanks for bringing it to our attention @ProtocolCash !

**Closed by cgcardona** 2019-05-07 08:37 UTC
Labels: bug
